### ISSUE TITLE
Select interfaces

### ISSUE THREAD

**Issue by Nowaker** [dfaust/plasma-applet-netspeed-widget#1]
I'd like to exclude all the communication that happens on certain interfaces. For example - any communication on `docker0` because it's mostly communication to `lo`. Therefore, I'd like to select interfaces I want shown on the widget, and I'd select `eth0` and `wlan0`.

BTW - best netspeed widget in KDE!

**Comment by dfaust** [comment]
Yeah, that has been on my TODO list for a long time now, so I won't make any promises.

> BTW - best netspeed widget in KDE!

Thank you!

**Comment by ghost** [comment]
Yes, I want this feature as well, in my case I have a interface for my VPN connection that "replicates" every traffic that passes from my main ethernet interface, now the applet is showing doubled speed values, I'd like to select which interfaces I want to monitor.

**Comment by Nowaker** [comment]
Hey @dfaust, thanks for doing it. You rock! When will this show up in [KDE Store](https://store.kde.org/p/998895)?

**Comment by dfaust** [comment]
@Nowaker It should already, I uploaded the new version there right after pushing it to github.

**Comment by Nowaker** [comment]
@dfaust It might be a stupid question but... how do I update it? I go to "Download New Plasma Widgets", I download yours (the new version showed up in KDE Store 5 days after you pushed it there), but there's no effect. The widget configuration window has no new stuff. And when I restart KDE, plasma widgets thingy doesn't consider the latest version of your widget installed. Thanks.

**Comment by ghost** [comment]
In my case I had to remove and uninstall the widget first, re-login from my KDE session, get back and reinstall the widget to get the update.

![screenshot_20170721_152744](https://user-images.githubusercontent.com/20016536/28477164-2b6ffbf2-6e29-11e7-92c1-2d164025c30b.png)

**Comment by Nowaker** [comment]
Thanks @chmercesmoreira!

**Comment by dfaust** [comment]
Well that sucks. Not sure what I can do about that though.
I hope re-installing works. Thank you @chmercesmoreira.
