### ISSUE TITLE
horizontal layout option for netspeed

### ISSUE THREAD

**Issue by CoreJa** [dfaust/plasma-applet-netspeed-widget#13]
Thank you for your cool widget. Used it for a while.
Using a version of 1.5 from KDE store.

I'm using a global panel on KDE, and tried to add this cool thing to my 28px height global panel. And it's way too small to recognize. Having Searched through the whole settings and still couldn't find an option for a horizontal layout.
![image](https://user-images.githubusercontent.com/28624864/57934316-0bfc1780-78f2-11e9-96cb-f8ad615e7c1f.png)

But it'll be squeezed to horizontal layout when adjusting the height to 20px or below which will make the panel too narrow.
![image](https://user-images.githubusercontent.com/28624864/57934799-018e4d80-78f3-11e9-964b-6a75ca529dc6.png)

I'm not a qt developer and don't have the time learning to develop it for now. So I'm really looking forward to a horizontal layout option. That'll helps a lot for our global panel users.
Thank you again!

**Comment by dfaust** [comment]
The applet switches to single line mode when the font size would get smaller than the minimum font size set in the kde settings.
But I agree, having a setting to overwrite the layout is a good idea. I will release an update in a minute, it might take a while though until the kde store is updated.

**Comment by CoreJa** [comment]
That was really cool!
Already updated my widget. Looks great.
![image](https://user-images.githubusercontent.com/28624864/57962880-4a73ef80-794f-11e9-939c-723fa29e4674.png)
