### ISSUE TITLE
digits are not centered in vertical panels.

### ISSUE THREAD

**Issue by safeer-pasha** [dfaust/plasma-applet-netspeed-widget#14]
![Screenshot_20190726_160021](https://user-images.githubusercontent.com/53339274/64092710-1f30d700-cd6b-11e9-9a05-b0d9b02aa3ab.png)
![Screenshot_20190727_171924](https://user-images.githubusercontent.com/53339274/64092746-3ec7ff80-cd6b-11e9-8c87-503bd9bcbd46.png)
![Screenshot_20190727_171939](https://user-images.githubusercontent.com/53339274/64092747-3f609600-cd6b-11e9-9a4c-58f5d5e8acea.png)

if the digits get centered, they will look more appealing and more polished.

**Comment by dfaust** [comment]
Sorry for the late answer. The reason the digits are not centered is that they would move around as the numbers change. I think that would be too distracting.
