### ISSUE TITLE
Poorly rendered fonts (with fix)

### ISSUE THREAD

**Issue by Focshole** [dfaust/plasma-applet-netspeed-widget#17]
Good Evening,
As first I'd like to thank you for this awesome work, it works very well. The only issue I have found is on font rendering. As you can see here:
![Image_poorly_rendered](https://user-images.githubusercontent.com/35631729/67413391-57150780-f5c1-11e9-86d5-0285952f306e.png)
I have fixed it by adding the property `renderType: Text.NativeRendering` to Text units with id TopText, topUnitText, bottomText,bottomUnitText in file CompactRepresentation.qml. The result is:
![Image_well_rendered](https://user-images.githubusercontent.com/35631729/67413712-f76b2c00-f5c1-11e9-9d4b-3973830ec02f.png)
Which is much more clear to read.

**Comment by dfaust** [comment]
Thank you. I hope this won't break anything. It doesn't make a difference on my system.

**Comment by dfaust** [comment]
@Focshole Do you have this problem with other QML widgets as well?

**Comment by Focshole** [comment]
This was the worst rendering one. From the manual https://doc-snapshots.qt.io/qt5-5.9/qml-qtquick-text.html#renderType-prop it says:

> Select Text.NativeRendering if you prefer text to look native on the target platform and do not require advanced features such as transformation of the text. Using such features in combination with the NativeRendering render type will lend poor and sometimes pixelated results.

After noticing that no text transformations have been applied in the plasmoid code, i thought it could work. It was poorly rendering also on a laptop of a friend of mine.
