### ISSUE TITLE
Not displaying info on Fedora KDE.

### ISSUE THREAD

**Issue by AndrewPrzelucki** [dfaust/plasma-applet-netspeed-widget#19]
Stopped working lately, the widget only shows 0.0 download and upload. Worked great until that. The popup seems to be working fine, my devices are showing and it does show how much I downloaded or uploaded. I tried to change the settings a few times, and even removed the widget and added again to my taskbar, but no change. I use a wired Ethernet connection - I connect my phone to my PC via USB cable. I update my OS every day, so everything is up to date.

The KDE connections widget shows everything working properly, I have speed information and all. I also used a Wi-Fi connection and again, the KDE connections widget works fine, but your widget does not work, in fact it stopped working completely when I went on Wi-Fi.

**Comment by AndrewPrzelucki** [comment]
I restarted my PC and it's working again. This started not too long ago, it worked constantly before. So at some point your widget - plasmoid - stops showing the traffic speeds, but as I said before, the popup information does work and shows how much I downloaded or uploaded. But sometimes, even restarting does not help. My connections are fine though, no interrupts or breakups or anything, it's just the widget that stopped showing me this necessary info.

**Comment by dfaust** [comment]
Thanks for reporting this issue. Unfortunately I don't see what I could do about that. It seems like a problem with the data source or the renderer. The widget itself simply is not that complicated so I don't see how it could cause such a bug.
