### ISSUE TITLE
Widget don't work with KDE and Arch linux

### ISSUE THREAD

**Issue by realOgenki** [dfaust/plasma-applet-netspeed-widget#21]
Previously it did works, but now show an error when you launch it:

Error al cargar archivo QML: file:///usr/share/plasma/plasmoids/org.kde.netspeedWidget/contents/ui/main.qml:45:37: Type CompactRepresentation unavailable
file:///usr/share/plasma/plasmoids/org.kde.netspeedWidget/contents/ui/CompactRepresentation.qml:20:1: module "org.kde.plasma.private.quicklaunch" is not installed

**Comment by dfaust** [comment]
Thank you for reporting this. You are missing a package.

On Arch Linux, I think it's [kdeplasma-addons](https://www.archlinux.org/packages/extra/x86_64/kdeplasma-addons/).

Please let me know if installing it fixes the problem.

**Comment by realOgenki** [comment]
Yes! this is the missing package. Thank you very much.
¿Can you include this dependence for avoid the issue on other users?
Regards.

**Comment by dfaust** [comment]
Starting with version 1.9 the quicklaunch dependency is optional. If it's not installed the "Launch application when clicked" option will be disabled and an information text will be shown.

![grafik](https://user-images.githubusercontent.com/893710/92155141-31829c80-ee27-11ea-8d24-a910d5241bc1.png)

**Comment by realOgenki** [comment]
Great. And when you try to install the widget, it will advice that this dependency is needed not optional:

![Screenshot_20200904_113311](https://user-images.githubusercontent.com/33685025/92225163-21100780-eea3-11ea-919e-f8b591761826.jpg)
