### ISSUE TITLE
Add File Browser to „Launch application when clicked”

### ISSUE THREAD

**Issue by alekksander** [dfaust/plasma-applet-netspeed-widget#22]
Could we please have an option to browser for something different rather than an app from indexed applications? i'd like to point it to launch a script with „vnstat -d” or something similar.

**Comment by dfaust** [comment]
I'm sorry, but that's out of scope for this widget.
You can always add a script to your applications using the kde menu editor. 
The benefit of this is, that the kde menu editor already provides all the settings like `launch in a terminal`, etc.

**Comment by alekksander** [comment]
works like a charm. me stupid never think it
thanks!

(to prevent some confusion: remember to set „--noclose” in terminal options like this:
![Screenshot_20210207_131206](https://user-images.githubusercontent.com/3148302/107146087-f268f200-6956-11eb-9baa-0686dce93420.png))
