### ISSUE TITLE
The widget cannot display the netspeed correctly in new version of plasma

### ISSUE THREAD

**Issue by levihuayuzhang** [dfaust/plasma-applet-netspeed-widget#28]
Thanks for reading.

Operating System: Arch Linux
KDE Plasma Version: 5.22.1
KDE Frameworks Version: 5.83.0
Qt Version: 5.15.2
Kernel Version: 5.12.10-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 5800H with Radeon Graphics
Memory: 15.1 GiB of RAM
Graphics Processor: AMD RENOIR

The WI-FI adapter: Intel AX200
Widget version: 1.9

The widget does not work neither build from source or installed in Plasma's `Get New Widget`. The widget just show the netspeed of upload and download as `0 kb/s` all the tiime.

**Comment by kamfretoz** [comment]
I am having the same problem as well, it looks like the applet are unable to detect the network Interface..
![Screenshot_20210617_202226](https://user-images.githubusercontent.com/14798312/122404951-2b514d00-cf6f-11eb-8564-badefcc51cf1.png)

**Comment by potatogod3000** [comment]
I too have this problem :(

**Comment by dfaust** [comment]
Thanks for reporting this issue, I'll have a look at it on the weekend.

**Comment by potatogod3000** [comment]
Thank you :) 
This problem only started occurring after updating Plasma to 5.22. This also occurs in another widget named Network Monitor (https://store.kde.org/p/998914/)

**Comment by jansuX2** [comment]
I assume it's related to `ksysguard` as a backend, which is no longer a dependency for `plasma-systemmonitor`, so it should be tied to `ksystemstats` instead. (If I install `ksysguard` the widget works as before)

https://archlinux.org/packages/extra/x86_64/plasma-systemmonitor/

**Comment by potatogod3000** [comment]
Yes! I can confirm it. I installed ksysguard and now it works as intended :)

**Comment by dfaust** [comment]
Looks like the library that is needed is `libKSysGuardSensorFaces.so`, which is part of the package `libksysguard` on Arch Linux (`libksysguard5` on openSUSE).
On openSUSE the package `plasma5-workspace` requires this lib. On Arch Linux that's not the case. The dependency for `ksysguard` has been removed recently (https://github.com/archlinux/svntogit-packages/commit/70e4af01582b90d2bff65ca67b3917751a016cc1#diff-3e341d2d9c67be01819b25b25d5e53ea3cdf3a38d28846cda85a195eb9b7203a).
Maybe it should have been replaced with a dependency on `libksysguard`.

Are you all using Arch Linux?
Does it work when removing `ksysguard` but keeping `libksysguard`?

**Comment by dfaust** [comment]
Also `plasma-workspace` contains the `systemmonitor` engine, which is used by `plasma-applet-netspeed-widget`.
I'm curious what happens if you inspect it with `plasmaengineexplorer`. I guess it should throw an error if `libksysguard` is not installed. Would someone on Arch Linux like to try this?

**Comment by levihuayuzhang** [comment]
> Looks like the library that is needed is `libKSysGuardSensorFaces.so`, which is part of the package `libksysguard` on Arch Linux (`libksysguard5` on openSUSE).
> On openSUSE the package `plasma5-workspace` requires this lib. On Arch Linux that's not the case. The dependency for `ksysguard` has been removed recently ([archlinux/svntogit-packages@70e4af0#diff-3e341d2d9c67be01819b25b25d5e53ea3cdf3a38d28846cda85a195eb9b7203a](https://github.com/archlinux/svntogit-packages/commit/70e4af01582b90d2bff65ca67b3917751a016cc1#diff-3e341d2d9c67be01819b25b25d5e53ea3cdf3a38d28846cda85a195eb9b7203a)).
> Maybe it should have been replaced with a dependency on `libksysguard`.
> 
> Are you all using Arch Linux?
> Does it work when removing `ksysguard` but keeping `libksysguard`?

On the current version of Arch Linux, if only has `libksysguard` installed, the widget seems doesn't work. But, after I installed `ksysguard`, the widget just back alive😄. I guess the widget maybe need `ksysguard` in someway.

**Comment by carmilso** [comment]
Same than @Tanche-Z here. With Arch Linux, libksysguard doesn't make the widget work. So the only way to make it work now is to install ksysguard :(

**Comment by cathaysia** [comment]
This bus appear to Fedrao 34 also. And install ksysguard/libksysguard can't solve this problem. Here are some logs that I can't comfirm is asseciation with netpseed:

```log
org.kde.ksysguard.plugin.network: Helper process terminated abnormally!
org.kde.ksysguard.plugin.network: "The process doesn't have permission to open the capture source\n"
```

**Comment by cathaysia** [comment]
> This bus appear to Fedrao 34 also. And install ksysguard/libksysguard can't solve this problem. Here are some logs that I can't comfirm is asseciation with netpseed:
> 
> ```
> org.kde.ksysguard.plugin.network: Helper process terminated abnormally!
> org.kde.ksysguard.plugin.network: "The process doesn't have permission to open the capture source\n"
> ```

Sorry, install package ksysguard can solve this bug, but a reboot needed.

**Comment by carmilso** [comment]
Is there any plan to fix this with no need to install `ksysguard`?. Just to know

**Comment by dfaust** [comment]
> Is there any plan to fix this with no need to install `ksysguard`?. Just to know

I don't think that's possible. It looks like `ksysguard` contains the data engine (which is weird). But I will try to add a warning if the data engine doesn't exist. I just don't know when I will have time for that.

**Comment by ekremx25** [comment]
> Is there any plan to fix this with no need to install `ksysguard`?. Just to know

i setup it arch linux working better...

**Comment by Freeedim** [comment]
Still doesn't work with 5.23.3. I use Debian Testing, which does not offer ksysguard in its repositories anymore. So I guess no solution at all for me right now.

**Comment by DarwinDemian** [comment]
I'm having the same problem here and if I install ksysguard then my wifi doesn't work.

**Comment by dfaust** [comment]
Just a quick status update. The widget must be ported to the Sensor [1] API.
If somebody wants to take a stab at it, they are welcome. I cannot promise that I will find the time.

[1] https://api.kde.org/plasma/libksysguard/html/classKSysGuard_1_1Sensor.html

**Comment by Ahmed-E-86** [comment]
`Ksysguard` is not available to install anymore (Kubuntu 22.04)

**Comment by wokawoka** [comment]
Any suggestion on how to use netspeed on Kubuntu 22.04 (no ksysguard installable)?
I'm missing it so much ...

**Comment by wokawoka** [comment]
I manually downloaded and installed ksysguard and its dependencies from https://packages.ubuntu.com/ and now netspeed widget works correctly
see [here](https://www.reddit.com/r/kde/comments/u9sws7/just_installed_kubuntu_2204_and_i_cant_use_the/)

**Comment by ppwwyyxx** [comment]
Was this fixed or not?

**Comment by dfaust** [comment]
No, it's not fixed.

**Comment by TXLogic** [comment]
I'm running KDE/Plasma 5.27.4 on both Ubuntu 22.10 and Kali Linux 2023.1 (both are running in Parallels VMs on a MacBook Pro with Apple Silicon using the recommended Shared Networking). The network speed widget works great under Kali but not under Ubuntu. The perhaps key difference between the two is that the ethernet interface in Ubuntu is enp0s5 and in Kali it's eth0, which I believe indicates that Ubuntu is using Netplan while Kali is using the traditional networking protocol. Perhaps this is helpful in identifying and hopefully solving the problem. (I notice that the System Monitor under Ubuntu is also not able to see enp0s5.) It would be super to get this nice widget functioning again under Ubuntu!

**Comment by Hentioe** [comment]
This problem has existed for a long time in NixOS. Installing `ksysguard` (`libksysguard`) has no effect. Does anyone use NixOS? Is there a solution to this problem?

**Comment by dfaust** [comment]
Hey everybody. Thank you very much for your interest in the netspeed widget.
I'm sorry, that it took so very long to fix this issue.
I just released version 2.0, which uses Linux's `/proc/net/dev` interface and I hope that it works for everybody.
If you still have issues, please don't hesitate to open a new issue.

**Comment by Freeedim** [comment]
> Hey everybody. Thank you very much for your interest in the netspeed widget. I'm sorry, that it took so very long to fix this issue. I just released version 2.0, which uses Linux's `/proc/net/dev` interface and I hope that it works for everybody. If you still have issues, please don't hesitate to open a new issue.

@dfaust I updated to v2.0 but nothing changed on my up-to-date Debian testing (Plasma 5.27.5). Both upload and download values are still stuck to 0. Should I open a new issue?

**Comment by dfaust** [comment]
> Should I open a new issue?

Yes, please.

**Comment by afc54** [comment]
Debian 12.4.  As of this date (1/15/24) the netspeed plasmoid still doesn't work, but one called "network usage", that looks exactly the same (needs to be DLed from the "Get New Widgets" -> "Download New Plasma Widgets") works fine, with this caveat.  It apparently grabs the kernel interface file/pipe exclusively, which means that if it is started first, it works but prevents another plasmoid: Network Speed from getting data.  If "Network Speed" is started first, it works but prevents "Network usage" from getting data.  So, as long as you have only one plasmoid getting network speeds it works fine.  Happily using "Network usage" as I type.
