### ISSUE TITLE
Not work on new plasma version 5.22.4

### ISSUE THREAD

**Issue by tarikmanoar** [dfaust/plasma-applet-netspeed-widget#30]
Can you fixed it bro

**Comment by barfin** [comment]
same
it doesn't show any network adaptor

**Comment by ghost** [comment]
you should install ksysguard
https://github.com/dfaust/plasma-applet-netspeed-widget/issues/28#issuecomment-863841712

**Comment by tarikmanoar** [comment]
It's remove in new updates 😉
It takes too much memory 😝

**Comment by superbonaci** [comment]
Same problem here with Ubuntu 21.10:
```
Operating System: Kubuntu 21.10
KDE Plasma Version: 5.22.5
KDE Frameworks Version: 5.86.0
Qt Version: 5.15.2
Kernel Version: 5.13.0-20-generic (64-bit)
Graphics Platform: X11
```
It displays 0.0 B/s on system tray.

**Comment by Zorrototo** [comment]
Did you read previous comment?

It works fine on Plasma 5.23.2 here.

**Comment by tarikmanoar** [comment]
> Did you read previous comment?
> 
> It works fine on Plasma 5.23.2 here.

Where?
I didn't notice

**Comment by weaksloth** [comment]
> you should install ksysguard [#28 (comment)](https://github.com/dfaust/plasma-applet-netspeed-widget/issues/28#issuecomment-863841712)

Good,it's useful

**Comment by PavelLetskii** [comment]
May be it worth to put the info about ksysguard in the README.

**Comment by Zorrototo** [comment]
done https://github.com/dfaust/plasma-applet-netspeed-widget/pull/32

**Comment by abolast** [comment]
> you should install ksysguard [#28 (comment)](https://github.com/dfaust/plasma-applet-netspeed-widget/issues/28#issuecomment-863841712)

thanks，it's useful!

**Comment by vivekkj123** [comment]
ksysguard has been removed from debian archives. So we need to consider other ways for implementing netspeed widget.

**Comment by dfaust** [comment]
I'm closing this issue in favor of #28.
