### ISSUE TITLE
Plasma netspeed widget stopped working 

### ISSUE THREAD

**Issue by samkulu** [dfaust/plasma-applet-netspeed-widget#37]
Dear Daniel Faust, 

I love your widget. Actually it is the first thing I always install on a linux machine. And I recommend everybody to use it. 

Unfortunately it stopped working and first I did not  know why exactly.  But now this  article seems to explain the reason: [Just installed Kubuntu 22.04, and I can't use the netspeed widget because it needs Ksysguard ...](https://www.reddit.com/r/kde/comments/u9sws7/just_installed_kubuntu_2204_and_i_cant_use_the/)

So far I am using another widget called Network speed. But I like your widget more.  

B.R.
Samuel 

P.S.: With `sudo apt install ksysguard` there arrives the message:

```
Package ksysguard is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libkf5sysguard-bin ksystemstats

E: Package 'ksysguard' has no installation candidate
```

**Comment by samkulu** [comment]
Actually I have only reinstalled over muon the following libraries:
- `qml-module-org-kde-ksysguard`
- `libksysguardformatter1`
- `libksysuardsensors1`
- `libksysguardsensorfaces1`

With `sudo apt install ksysguard` there arrives the message:

```
Package ksysguard is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libkf5sysguard-bin ksystemstats

E: Package 'ksysguard' has no installation candidate
```

So far I am using another widget called `Network speed`. But I like your widget more.

**Comment by samkulu** [comment]
Ok. This is article explains the reason:
[Just installed Kubuntu 22.04, and I can't use the netspeed widget because it needs Ksysguard ...](https://www.reddit.com/r/kde/comments/u9sws7/just_installed_kubuntu_2204_and_i_cant_use_the/)

**Comment by dfaust** [comment]
Unfortunately the plasma data engine which was part of ksysguard has been removed.
Have a look at https://github.com/dfaust/plasma-applet-netspeed-widget/issues/28#issuecomment-1076718739 for more infos.
