### ISSUE TITLE
no interfaces under advanced to select from - debian 9

### ISSUE THREAD

**Issue by gbil** [dfaust/plasma-applet-netspeed-widget#4]
So I installed the widget from your page yet I see no network interfaces to select - just an empty list and can't see anything in the log files. 

any ideas?

**Comment by dfaust** [comment]
The widget uses the `systemmonitor` data engine, provided by Plasma. You can see all available data engines using the `plasmaengineexplorer`.
Look for data sources matching the pattern `^network\/interfaces\/(\w+)\/(receiver|transmitter)\/data$`. Are there any?

And is this just any issue with the config dialog or isn't any network activity displayed at all?

**Comment by gbil** [comment]
Nothing was displayed, your comment drove me to the correct direction, the systemmonitor data engine was empty and I found I had to install **ksysguard** package which is not installed by default on debian 9 also when you install the base kde packages. Now everything works fine, thanks.
