### ISSUE TITLE
Displayed upload and download speeds remain 0 whatever the actual traffic is.

### ISSUE THREAD

**Issue by Freeedim** [dfaust/plasma-applet-netspeed-widget#41]
I use an up-to-date Debian Testing with Plasma (currently v5.27.5).
If I add a netspeed widget in the panel, both download and upload values remain stuck at "0", even if I am downloading or uploading something (that ends successfully, which proves there _was_ traffic).

**Comment by dfaust** [comment]
Can you please post the output of: `plasmawindowed org.kde.netspeedWidget`

**Comment by Freeedim** [comment]
Well, I don't know what to think. I had removed the widget before you wrote the answer. In order to answer you, I re-added it, and now it works. Of course, I had already removed and re-added it after the update to v2.

So I guess this issue can be closed

**Comment by dfaust** [comment]
Great!
