### ISSUE TITLE
Network speeds seem be multiplied by update interval

### ISSUE THREAD

**Issue by ddceca** [dfaust/plasma-applet-netspeed-widget#42]
I had update interval set to 2 seconds, and today I noticed that my download speed was unusually high. After doing some tests and comparing with other network speed measuring methods, it seems to me that the speeds reported by Netspeed Widget are possibly multiplied by the update interval.

For example: download a large file (I'm doing these tests with a kubuntu iso) which gives you a somewhat constant speed. In my case, it's about 2.3 MB/s. So, if I set the update interval to 10 seconds, I get a reported speed of about 23 MB/s.

I have Netspeed Widget 1.9 in:
Operating System: openSUSE Tumbleweed 20231006
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.10
Kernel Version: 6.5.4-1-default (64-bit)

**Comment by dfaust** [comment]
1. The data source has been completely rewritten in version 2.0 so you should update to that version.
2. When opening the settings dialog - for some reason I haven't figured out, yet - the `speed unit` setting is automatically set to `bits`. So you may want to change that to `bytes`.

**Comment by ddceca** [comment]
Thank you, I hadn't noticed there was a 2.0 version. I can confirm that, indeed, the problem I was reporting is solved with the new data source.

BTW, I'm not seeing the bytes -> bits problem. Every time I open the settings, the speed unit set to bytes is remembered correctly.

**Comment by dfaust** [comment]
> BTW, I'm not seeing the bytes -> bits problem

Thanks, good to know.
