### ISSUE TITLE
Support Plasma 6 (Port to KF6)

### ISSUE THREAD

**Issue by debnath-d** [dfaust/plasma-applet-netspeed-widget#43]
Please port this widget to KDE Framework 6. The guidelines are [here](https://develop.kde.org/docs/plasma/widget/porting_kf6/).

**Comment by giostark** [comment]
Is a very useful tool that allow to have a quick feedback on the net transfer status ... Hope that will be maintained :-)
Edit:
For the ones that are using plasma 6 , here the porting (that work):
Source:
https://forum.archlinux.de/d/35150-netspeed-widget-plasma-6
Download:
[plasma-applet-netspeed-widget-plasma6.zip](https://github.com/dfaust/plasma-applet-netspeed-widget/files/14545887/plasma-applet-netspeed-widget-plasma6.zip)

**Comment by simondvt** [comment]
> Is a very useful tool that allow to have a quick feedback on the net transfer status ... Hope that will be maintained :-) Edit: For the ones that are using plasma 6 , here the porting (that work): Source: [forum.archlinux.de/d/35150-netspeed-widget-plasma-6](https://forum.archlinux.de/d/35150-netspeed-widget-plasma-6) Download: [plasma-applet-netspeed-widget-plasma6.zip](https://github.com/dfaust/plasma-applet-netspeed-widget/files/14545887/plasma-applet-netspeed-widget-plasma6.zip)

I'm running KDE 6.0.1 and I get this error installing the widget in the zip:

> file:///home/user/.local/share/plasma/plasmoids/org.kde.netspeedWidget/contents/ui/main.qml:52:5: PlasmaCore.DataSource is not a type

**Comment by giostark** [comment]
Hi , I don't know ...
$ yay -Qss plasma-workspace
local/plasma-workspace 6.0.1-1 (plasma)
I'm under arch linux and it worked.  
Do you have the plasma-systemmonitor installed?
Seems that this widget make a call of what the system monitor gather from the system.
The PlasmaCore.DataSource share info so that multiple app do not work for gather from the system the same information already available.
https://www.reddit.com/r/kde/comments/gqfs9u/widgets_development_plasmacoredatasource_what_is/

**Comment by dfaust** [comment]
I released the kf6 version. Try this: https://www.pling.com/p/2136505/

**Comment by simondvt** [comment]
> I released the kf6 version. Try this: [pling.com/p/2136505](https://www.pling.com/p/2136505/)

This worked, thanks!

@giostark I do have plasma-workspace 6.0.1-1 and plasma-systemmonitor 6.0.1-1.

**Comment by dfaust** [comment]
To be clear. Since version 2.0, `netspeed-widget` doesn't need any additional plasma package.
`/proc/net/dev` is used as data source.

**Comment by giostark** [comment]
Thanks dfaust for your time and work :-)

**Comment by giostark** [comment]
Hi all ,
Today I tried to download and  install this widget to my laptop but it end with this issue :
`file:///home/ios/.local/share/plasma/plasmoids/org.kde.netspeedWidget/contents/ui/main.qml:52:5: PlasmaCore.DataSource is not a type`
The "install" from https://www.opendesktop.org/p/2136505/ via install report : 
`invalid OCS URL`
The old zip linked above do not work either. 
Installing it from source report the same first issue.

Suggestions ?
Thanks :-)

**Comment by Croydon** [comment]
This seems to be done.

I was able to re-install the widget from the KDE Store, added the widget once more to my panel, and then removed the old one.

I am not entirely sure if I have now an old installed package/widget that I could remove, but I haven't found such a thing yet. So did the new install replace the old one?

Thank you for all the work on this widget!

**Comment by dfaust** [comment]
> So did the new install replace the old one?

Yes, that should be the case.
