### ISSUE TITLE
Text of unit gets clipped

### ISSUE THREAD

**Issue by qwfy** [dfaust/plasma-applet-netspeed-widget#6]
The letter "M" in the unit, gets clipped:
![network speed widget text the letter m in the unit gets clipped](https://user-images.githubusercontent.com/11158705/44636059-07967400-a9dc-11e8-8422-2f0c29bb6c9b.png)

and here is the configuration:
![network speed widget text the letter m in the unit gets clipped configuration](https://user-images.githubusercontent.com/11158705/44636058-06fddd80-a9dc-11e8-9abb-d39cf9607a35.png)

**Comment by dfaust** [comment]
The fix I just pushed is not perfect. I think there is something wrong with the way the text sizes are calculated by Qt.
Anyway, I will release a new version soon. If the clipping still happens for you, then please re-open the issue.

**Comment by dfaust** [comment]
I just released version 1.6 with a few more tweaks. Please let me know if you still experience any issues.
